apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1024M
              cpu: 0.25
            limits:
              memory: 1024M
              cpu: 0.25
