apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1024Mi
              cpu: 2
            limits:
              memory: 1024Mi
              cpu: 2

          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 9300
            initialDelaySeconds: 15
            periodSeconds: 20
