apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1024Mi
              cpu: 2
            limits:
              memory: 2048Mi
              cpu: 2

          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 10
  
          livenessProbe:
            tcpSocket:
              port: 9300
            initialDelaySeconds: 60
            periodSeconds: 20

  volumeClaimTemplates:
  - metadata:
      name: es-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
