apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    service: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kibana
  template:
    metadata:
      labels:
        service: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.15.1
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
