apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  ports:
  - port: 9200
    name: elasticsearch-api
  - port: 9300
    name: elasticsearch-transport
  clusterIP: None
  selector:
    service: elasticsearch
