apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      service: elasticsearch
  serviceName: elasticsearch
  replicas: 3
  podManagementPolicy: Parallel
  template: 
    metadata:
      labels:
        service: elasticsearch
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-storage
          mountPath: /usr/share/elasticsearch/data
        readinessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 300
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9300
          initialDelaySeconds: 300
          periodSeconds: 20
        resources:
          requests:
            memory: 1024M
            cpu: 1
          limits:
            memory: 1024M
            cpu: 1
        env:
        - name: discovery.zen.ping.unicast.hosts
          value: "elasticsearch"

        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        - name: node.roles
          value: "master,data"

        - name: cluster.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service']

        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"

        - name: node.store.allow_mmap
          value: "false"

        - name: cluster.initial_master_nodes
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        - name: cluster.initial_master_nodes
          value: "elasticsearch-0,elasticsearch-1,elasticsearch-2"
  volumeClaimTemplates:
  - metadata:
      name: es-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500M
