apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      service: elasticsearch
  serviceName: elasticsearch
  replicas: 1
  template: 
    metadata:
      labels:
        service: elasticsearch
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
        ports:
        - containerPort: 9200
          name: es
        volumeMounts:
        - name: es-storage
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: node.roles
          value: "master,data"
        - name: cluster.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service']
        - name: ES_JAVA_OPTS
          value: "-Xms1024m -Xmx1024m"
        - name: node.store.allow_mmap
          value: "false"
        - name: cluster.initial_master_nodes
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: 1024M
            cpu: 0.2
          limits:
            memory: 1024M
            cpu: 0.5
  volumeClaimTemplates:
  - metadata:
      name: es-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500M
