apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      service: elasticsearch
  serviceName: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        service: elasticsearch
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
        ports:
        - containerPort: 9200
          name: es
        volumeMounts:
        - name: es-storage
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # - name: cluster.name
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: metadata.labels["service"]
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        resources:
          requests:
            memory: 1024M
            cpu: 0.2
          limits:
            memory: 1024M
            cpu: 0.5
  volumeClaimTemplates:
  - metadata:
      name: es-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500M
