apiVersion: v1
kind: Pod
metadata:
  labels:
    run: debug
  name: debug
spec:
  containers:
  - image: alpine
    name: debug
    command:
      - sleep
      - "6000"
  dnsPolicy: ClusterFirst
  restartPolicy: Never

